produit_produit:
    resource: "@ProduitBundle/Resources/config/routing/produit.yml"
    prefix:   /produit

affiche:
    path:     /af
    defaults: { _controller: ProduitBundle:Default:index }
accueil:
    path:     /accueil
    defaults: { _controller: ProduitBundle:Default:index2 }
